import axios from 'axios';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import './onboarding-tour';
import './onboarding-replay-confirmation';
import './application-intake-flow';
import './application-page-cleanup';
import './staff-list-filters';
import './dashboard-work-queue';
import './staff-dashboard-hero';
import './parcel-map-single-tooltip';
import './geodetic-geometry-workflow';
import './account-panel';
import './user-management-linked-records';
import './staff-record-row-navigation';
import './responsive-hardening';
import './mobile-portal-polish';
import './ui-ux-system';
import './ui-ux-last-mile';
import './ui-ux-public';
import '../css/staff-dashboard-hero.css';
import '../css/application-page-cleanup.css';
import '../css/staff-list-filters.css';
import '../css/application-table-toolbar.css';
import '../css/filter-control-normalization.css';
import '../css/active-filter-alignment.css';
import '../css/geodetic-geometry-workflow.css';
import '../css/geodetic-responsive.css';
import '../css/password-recovery-spacing.css';
import '../css/account-panel-polish.css';
import '../css/user-management-linked-records.css';
import '../css/staff-record-row-navigation.css';
import '../css/responsive-hardening-last-mile.css';
import '../css/ui-ux-system.css';
import '../css/ui-ux-last-mile.css';
import '../css/application-modal-viewport.css';
import '../css/ui-ux-public.css';

window.axios = axios;
window.L = L;

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';