<?php

return [
    // Official PSGC reference: Philippine Statistics Authority, PSGC as of 30 June 2026.
    'province' => 'Negros Oriental',
    'municipalities' => [
        'Amlan' => ['Bio-os', 'Jantianon', 'Jugno', 'Mag-abo', 'Poblacion', 'Silab', 'Tambojangin', 'Tandayag'],
        'Ayungon' => ['Amdus', 'Jandalamanon', 'Anibong', 'Atabay', 'Awa-an', 'Ban-ban', 'Calagcalag', 'Candana-ay', 'Carol-an', 'Gomentoc', 'Inacban', 'Iniban', 'Kilaban', 'Lamigan', 'Maaslum', 'Mabato', 'Manogtong', 'Nabhang', 'Tambo', 'Tampocon I', 'Tampocon II', 'Tibyawan', 'Tiguib', 'Poblacion'],
        'Bacong' => ['Balayagmanok', 'Banilad', 'Buntis', 'Buntod', 'Calangag', 'Combado', 'Doldol', 'Isugan', 'Liptong', 'Lutao', 'Magsuhot', 'Malabago', 'Mampas', 'North Poblacion', 'Sacsac', 'San Miguel', 'South Poblacion', 'Sulodpan', 'Timbanga', 'Timbao', 'Tubod', 'West Poblacion'],
        'Bais City' => ['Barangay I', 'Barangay II', 'Basak', 'Biñohon', 'Cabanlutan', 'Calasga-an', 'Cambagahan', 'Cambaguio', 'Cambanjao', 'Cambuilao', 'Canlargo', 'Capiñahan', 'Consolacion', 'Dansulan', 'Hangyad', 'La Paz', 'Lo-oc', 'Lonoy', 'Mabunao', 'Manlipac', 'Mansangaban', 'Okiot', 'Olympia', 'Panala-an', 'Panam-angan', 'Rosario', 'Sab-ahan', 'San Isidro', 'Katacgahan', 'Tagpo', 'Talungon', 'Tamisu', 'Tamogong', 'Tangculogan', 'Valencia'],
        'Basay' => ['Actin', 'Bal-os', 'Bongalonan', 'Cabalayongan', 'Cabatuanan', 'Linantayan', 'Maglinao', 'Nagbo-alao', 'Olandao', 'Poblacion'],
        'Bayawan City' => ['Ali-is', 'Banaybanay', 'Banga', 'Villasol', 'Boyco', 'Bugay', 'Cansumalig', 'Dawis', 'Kalamtukan', 'Kalumboyan', 'Malabugas', 'Mandu-ao', 'Maninihon', 'Minaba', 'Nangka', 'Narra', 'Pagatban', 'Poblacion', 'San Jose', 'San Miguel', 'San Roque', 'Suba', 'Tabuan', 'Tayawan', 'Tinago', 'Ubos', 'Villareal', 'San Isidro'],
        'Bindoy' => ['Atotes', 'Batangan', 'Bulod', 'Cabcaban', 'Cabugan', 'Camudlas', 'Canluto', 'Danao', 'Danawan', 'Domolog', 'Malaga', 'Manseje', 'Matobato', 'Nagcasunog', 'Nalundan', 'Pangalaycayan', 'Peñahan', 'Poblacion', 'Salong', 'Tagaytay', 'Tinaogan', 'Tubod'],
        'Canlaon City' => ['Bayog', 'Binalbagan', 'Bucalan', 'Linothangan', 'Lumapao', 'Malaiba', 'Masulog', 'Panubigan', 'Mabigo', 'Pula', 'Budlasan', 'Ninoy Aquino'],
        'Dauin' => ['Anhawan', 'Apo Island', 'Bagacay', 'Baslay', 'Batuhon Dacu', 'Boloc-boloc', 'Bulak', 'Bunga', 'Casile', 'Libjo', 'Lipayo', 'Maayongtubig', 'Mag-aso', 'Magsaysay', 'Malongcay Dacu', 'Masaplod Norte', 'Masaplod Sur', 'Panubtuban', 'Poblacion I', 'Poblacion II', 'Poblacion III', 'Tugawe', 'Tunga-tunga'],
        'Dumaguete City' => ['Bagacay', 'Bajumpandan', 'Balugo', 'Banilad', 'Bantayan', 'Batinguel', 'Bunao', 'Cadawinonan', 'Calindagan', 'Camanjac', 'Candau-ay', 'Cantil-e', 'Daro', 'Junob', 'Looc', 'Mangnao-Canal', 'Motong', 'Piapi', 'Poblacion No. 1', 'Poblacion No. 2', 'Poblacion No. 3', 'Poblacion No. 4', 'Poblacion No. 5', 'Poblacion No. 6', 'Poblacion No. 7', 'Poblacion No. 8', 'Pulantubig', 'Tabuctubig', 'Taclobo', 'Talay'],
        'Guihulngan City' => ['Bakid', 'Balogo', 'Banwaque', 'Basak', 'Binobohan', 'Buenavista', 'Bulado', 'Calamba', 'Calupa-an', 'Hibaiyo', 'Hilaitan', 'Hinakpan', 'Humayhumay', 'Imelda', 'Kagawasan', 'Linantuyan', 'Luz', 'Mabunga', 'Mckinley', 'Nagsaha', 'Magsaysay', 'Malusay', 'Maniak', 'Padre Zamora', 'Plagatasanon', 'Planas', 'Poblacion', 'Sandayao', 'Tacpao', 'Tinayunan Beach', 'Tinayunan Hill', 'Trinidad', 'Villegas'],
        'Jimalalud' => ['Aglahug', 'Agutayon', 'Apanangon', 'Bae', 'Bala-as', 'Bangcal', 'Banog', 'Buto', 'Cabang', 'Camandayon', 'Cangharay', 'Canlahao', 'Dayoyo', 'Eli', 'Lacaon', 'Mahanlud', 'Malabago', 'Mambaid', 'Mongpong', 'Owacan', 'Pacuan', 'Panglaya-an', 'North Poblacion', 'South Poblacion', 'Polopantao', 'Sampiniton', 'Talamban', 'Tamao'],
        'La Libertad' => ['Aniniaw', 'Aya', 'Bagtic', 'Biga-a', 'Busilak', 'Cangabo', 'Cantupa', 'Eli', 'Guihob', 'Kansumandig', 'Mambulod', 'Mandapaton', 'Manghulyawon', 'Manluminsag', 'Mapalasan', 'Maragondong', 'Martilo', 'Nasungan', 'Pacuan', 'Pangca', 'Pisong', 'Pitogo', 'Poblacion North', 'Poblacion South', 'San Jose', 'Solongon', 'Tala-on', 'Talayong', 'Elecia'],
        'Mabinay' => ['Abis', 'Arebasore', 'Bagtic', 'Banban', 'Barras', 'Bato', 'Bugnay', 'Bulibulihan', 'Bulwang', 'Campanun-an', 'Canggohob', 'Cansal-ing', 'Dagbasan', 'Dahile', 'Himocdongon', 'Hagtu', 'Inapoy', 'Lamdas', 'Lumbangan', 'Luyang', 'Manlingay', 'Mayaposi', 'Napasu-an', 'New Namangka', 'Old Namangka', 'Pandanon', 'Paniabonan', 'Pantao', 'Poblacion', 'Samac', 'Tadlong', 'Tara'],
        'Manjuyod' => ['Alangilanan', 'Bagtic', 'Balaas', 'Bantolinao', 'Bolisong', 'Butong', 'Campuyo', 'Candabong', 'Concepcion', 'Dungo-an', 'Kauswagan', 'Libjo', 'Lamogong', 'Maaslum', 'Mandalupang', 'Panciao', 'Poblacion', 'Sac-sac', 'Salvacion', 'San Isidro', 'San Jose', 'Santa Monica', 'Suba', 'Sundo-an', 'Tanglad', 'Tubod', 'Tupas'],
        'Pamplona' => ['Abante', 'Balayong', 'Banawe', 'Datagon', 'Fatima', 'Inawasan', 'Magsusunog', 'Malalangsi', 'Mamburao', 'Mangoto', 'Poblacion', 'San Isidro', 'Santa Agueda', 'Simborio', 'Yupisan', 'Calicanan'],
        'San Jose' => ['Basak', 'Basiao', 'Cambaloctot', 'Cancawas', 'Janayjanay', 'Jilocon', 'Naiba', 'Poblacion', 'San Roque', 'Santo Niño', 'Señora Ascion', 'Siapo', 'Tampi', 'Tapon Norte'],
        'Santa Catalina' => ['Alangilan', 'Amio', 'Buenavista', 'Kabulacan', 'Caigangan', 'Caranoche', 'Cawitan', 'Fatima', 'Mabuhay', 'Manalongon', 'Mansagomayon', 'Milagrosa', 'Nagbinlod', 'Nagbalaye', 'Obat', 'Poblacion', 'San Francisco', 'San Jose', 'San Miguel', 'San Pedro', 'Santo Rosario', 'Talalak'],
        'Siaton' => ['Albiga', 'Apoloy', 'Bonawon', 'Bonbonon', 'Cabangahan', 'Canaway', 'Casala-an', 'Caticugan', 'Datag', 'Giliga-on', 'Inalad', 'Malabuhan', 'Maloh', 'Mantiquil', 'Mantuyop', 'Napacao', 'Poblacion I', 'Poblacion II', 'Poblacion III', 'Poblacion IV', 'Salag', 'San Jose', 'Sandulot', 'Si-it', 'Sumaliring', 'Tayak'],
        'Sibulan' => ['Agan-an', 'Ajong', 'Balugo', 'Bolocboloc', 'Calabnugan', 'Cangmating', 'Enrique Villanueva', 'Looc', 'Magatas', 'Maningcao', 'Maslog', 'Poblacion', 'San Antonio', 'Tubigon', 'Tubtubon'],
        'Tanjay City' => ['Azagra', 'Bahi-an', 'Luca', 'Manipis', 'Novallas', 'Obogon', 'Pal-ew', 'Poblacion I', 'Poblacion II', 'Poblacion III', 'Poblacion IV', 'Poblacion V', 'Poblacion VI', 'Poblacion VII', 'Poblacion VIII', 'Poblacion IX', 'Polo', 'San Isidro', 'San Jose', 'San Miguel', 'Santa Cruz Nuevo', 'Santa Cruz Viejo', 'Santo Niño', 'Tugas'],
        'Tayasan' => ['Bacong', 'Bago', 'Banga', 'Cabulotan', 'Cambaye', 'Dalaupon', 'Guincalaban', 'Ilaya-Tayasan', 'Jilabangan', 'Lag-it', 'Linao', 'Lutay', 'Maglihe', 'Matauta', 'Magtuhao', 'Matuog', 'Numnum', 'Palaslan', 'Pindahan', 'Pinalubngan', 'Pinocawan', 'Poblacion', 'Santa Cruz', 'Saying', 'Suquib', 'Tamao', 'Tambulan', 'Tanlad'],
        'Valencia' => ['Apolong', 'Balabag East', 'Balabag West', 'Balayagmanok', 'Balili', 'Balugo', 'Bongbong', 'Bong-ao', 'Calayugan', 'Cambucad', 'Dobdob', 'Jawa', 'Caidiocan', 'Liptong', 'Lunga', 'Malabo', 'Malaunay', 'Mampas', 'Palinpinon', 'North Poblacion', 'South Poblacion', 'Puhagan', 'Pulangbato', 'Sagbang'],
        'Vallehermoso' => ['Bagawines', 'Bairan', 'Don Espiridion Villegas', 'Guba', 'Cabulihan', 'Macapso', 'Malangsa', 'Molobolo', 'Maglahos', 'Pinocawan', 'Poblacion', 'Puan', 'Tabon', 'Tagbino', 'Ulay'],
        'Zamboanguita' => ['Basac', 'Calango', 'Lotuban', 'Malongcay Diot', 'Maluay', 'Mayabon', 'Nabago', 'Nasig-id', 'Najandig', 'Poblacion'],
    ],
];
